IF OBJECT_ID(N'Basketball.School') IS NULL
BEGIN
   CREATE TABLE Basketball.School
   (
	GameID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[DateTime] DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	RoundID INT NOT NULL FOREIGN KEY
		REFERENCES Basketball.[Round](RoundID)
   );
END
